#include "Patient.h"
#include <chrono> // including for handling time-related operations
#include <ctime> // including for converting time to a string representation
#include <sstream> // including for using ostringstream to build strings
#include <iomanip> // including for using stream manipulators

// defining and initializing the static member variable to zero
int Patient::amountOfPatients = 0;

// constructor for creating a fully detailed patient object
Patient::Patient(int p_severity, std::string p_name, char p_gender, int p_age, std::string p_department,
                 std::string p_complaints, std::string p_bloodGroup, std::string p_diagnosis)
    : patientId(++amountOfPatients), name(std::move(p_name)), diagnosis(std::move(p_diagnosis)), // using std::move for transferring ownership of string data efficiently
      complaints(std::move(p_complaints)), gender(p_gender), age(p_age), bloodGroup(std::move(p_bloodGroup)),
      severity(p_severity), department(std::move(p_department)), arrivalTime(std::chrono::system_clock::now()) // capturing the current system time as the arrival time
{}

// constructor for creating a patient with essential details and blood group
Patient::Patient(int p_severity, char p_gender, std::string p_name, int p_age, std::string p_department, std::string p_bloodGroup)
    : patientId(++amountOfPatients), name(std::move(p_name)), diagnosis("No Records"),
      complaints("Unspecified"), gender(p_gender), age(p_age), bloodGroup(std::move(p_bloodGroup)),
      severity(p_severity), department(std::move(p_department)), arrivalTime(std::chrono::system_clock::now())
{}

// constructor for creating a patient with full details, matching the order of the first constructor but with different parameter order
Patient::Patient(std::string p_name, int p_severity, char p_gender, int p_age, std::string p_department, std::string p_complaints, std::string p_bloodGroup, std::string p_diagnosis)
    : patientId(++amountOfPatients), name(std::move(p_name)), diagnosis(std::move(p_diagnosis)),
      complaints(std::move(p_complaints)), gender(p_gender), age(p_age), bloodGroup(std::move(p_bloodGroup)),
      severity(p_severity), department(std::move(p_department)), arrivalTime(std::chrono::system_clock::now())
{}

// default constructor for creating a patient with default values
Patient::Patient()
    : patientId(++amountOfPatients), name("Unknown"), diagnosis("No Records"),
      complaints("Unspecified"), gender('-'), age(0), bloodGroup("Unknown"),
      severity(0), department("General"), arrivalTime(std::chrono::system_clock::now())
{}

// using the default destructor generated by the compiler
Patient::~Patient() = default;

int Patient::getPatientId() const { return patientId; }
std::string Patient::getName() const { return name; }
int Patient::getSeverity() const { return severity; }
std::string Patient::getDiagnosis() const { return diagnosis; }
char Patient::getGender() const { return gender; }
int Patient::getAge() const { return age; }
std::string Patient::getBloodGroup() const { return bloodGroup; }
std::string Patient::getComplaints() const { return complaints; }
std::string Patient::getDepartment() const { return department; }
std::chrono::system_clock::time_point Patient::getArrivalTime() const { return arrivalTime; }

void Patient::setDiagnosis(const std::string &p_diagnosis) { diagnosis = p_diagnosis; }
void Patient::setBloodGroup(const std::string &bg) { bloodGroup = bg; }

std::string Patient::getStringArrivalTime() const {
    // converting a system_clock::time_point to a time_t object
    std::time_t t = std::chrono::system_clock::to_time_t(arrivalTime);
    std::tm tm{}; // creating a tm struct to hold the broken-down time
// using platform-specific thread-safe functions for converting time
#if defined(_MSC_VER) // checking for microsoft visual c++ compiler
    localtime_s(&tm, &t); // using the secure version of localtime for windows
#elif defined(__GLIBC__) // checking for gnu c library
    localtime_r(&t, &tm); // using the reentrant version of localtime for linux
#else
    tm = *std::localtime(&t); // using the standard localtime, which might not be thread-safe
#endif
    char buf[64]; // creating a buffer to store the formatted time string
    // formatting the time into a "YYYY-MM-DD HH:MM:SS" string
    std::strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", &tm);
    return std::string(buf);
}

std::string Patient::info() const {
    std::ostringstream oss; // creating a string stream for building the output string efficiently

    // defining ansi escape codes for coloring text in the console
    std::string red = "\033[1;31m";    // for styling text red
    std::string yellow = "\033[1;33m"; // for styling text yellow
    std::string green = "\033[1;32m";  // for styling text green
    std::string reset = "\033[0m";     // for resetting text style to default

    std::string severityColor = green; // setting default color to green
    if (severity >= 9) {
        severityColor = red;           // changing color to red for critical severity
    } else if (severity >= 5) {
        severityColor = yellow;        // changing color to yellow for moderate severity
    }

    // building the patient information string using the string stream
    oss << "Patient ID: " << getPatientId() << "\n"
        << "Name: " << getName() << "\n"
        << "Severity: " << severityColor << getSeverity() << reset << "\n"
        << "Department: " << getDepartment() << "\n"
        << "Arrival: " << getStringArrivalTime() << "\n"
        << "Gender: " << getGender() << "  Age: " << getAge() << "\n"
        << "Complaints: " << getComplaints() << "\n"
        << "Blood Group: " << getBloodGroup() << "\n"
        << "Diagnosis: " << getDiagnosis();
    return oss.str(); // returning the final composed string
}