#include "Patient.h"
#include <chrono> // including for handling time-related operations
#include <format> // for c++20 formatting
#include <sstream> // including for using ostringstream to build strings
#include <iomanip> // including for using stream manipulators

using namespace std;

// defining and initializing the static member variable to zero
int Patient::amountOfPatients = 0;

// constructor for creating a fully detailed patient object
Patient::Patient(int p_severity, string p_name, char p_gender, int p_age, string p_department,
                 string p_complaints, string p_bloodGroup, string p_diagnosis)
    : patientId(++amountOfPatients), name(move(p_name)), diagnosis(move(p_diagnosis)), // using move for transferring ownership of string data efficiently
      complaints(move(p_complaints)), gender(p_gender), age(p_age), bloodGroup(move(p_bloodGroup)),
      severity(p_severity), department(move(p_department)), arrivalTime(chrono::system_clock::now()) // capturing the current system time as the arrival time
{}

// constructor for creating a patient with essential details and blood group
Patient::Patient(int p_severity, char p_gender, string p_name, int p_age, string p_department, string p_bloodGroup)
    : patientId(++amountOfPatients), name(move(p_name)), diagnosis("No Records"),
      complaints("Unspecified"), gender(p_gender), age(p_age), bloodGroup(move(p_bloodGroup)),
      severity(p_severity), department(move(p_department)), arrivalTime(chrono::system_clock::now())
{}

// constructor for creating a patient with full details, matching the order of the first constructor but with different parameter order
Patient::Patient(string p_name, int p_severity, char p_gender, int p_age, string p_department, string p_complaints, string p_bloodGroup, string p_diagnosis)
    : patientId(++amountOfPatients), name(move(p_name)), diagnosis(move(p_diagnosis)),
      complaints(move(p_complaints)), gender(p_gender), age(p_age), bloodGroup(move(p_bloodGroup)),
      severity(p_severity), department(move(p_department)), arrivalTime(chrono::system_clock::now())
{}

// default constructor for creating a patient with default values
Patient::Patient()
    : patientId(++amountOfPatients), name("Unknown"), diagnosis("No Records"),
      complaints("Unspecified"), gender('-'), age(0), bloodGroup("Unknown"),
      severity(0), department("General"), arrivalTime(chrono::system_clock::now())
{}

// using the default destructor generated by the compiler
Patient::~Patient() = default;

int Patient::getPatientId() const { return patientId; }
string Patient::getName() const { return name; }
int Patient::getSeverity() const { return severity; }
string Patient::getDiagnosis() const { return diagnosis; }
char Patient::getGender() const { return gender; }
int Patient::getAge() const { return age; }
string Patient::getBloodGroup() const { return bloodGroup; }
string Patient::getComplaints() const { return complaints; }
string Patient::getDepartment() const { return department; }
chrono::system_clock::time_point Patient::getArrivalTime() const { return arrivalTime; }

void Patient::setDiagnosis(const string &p_diagnosis) { diagnosis = p_diagnosis; }
void Patient::setBloodGroup(const string &bg) { bloodGroup = bg; }

string Patient::getStringArrivalTime() const {
    return std::format("{:%Y-%m-%d %H:%M:%S}", arrivalTime);
}

string Patient::info() const {
    ostringstream resultingString; // creating a string stream for building the output string efficiently

    // defining ansi escape codes for coloring text in the console
    string red = "\033[1;31m";    // for styling text red
    string yellow = "\033[1;33m"; // for styling text yellow
    string green = "\033[1;32m";  // for styling text green
    string reset = "\033[0m";     // for resetting text style to default

    string severityColor = green; // setting default color to green
    if (severity >= 9) {
        severityColor = red;           // changing color to red for critical severity
    } else if (severity >= 5) {
        severityColor = yellow;        // changing color to yellow for moderate severity
    }

    // building the patient information string using the string stream
    resultingString << "Patient ID: " << getPatientId() << "\n"
        << "Name: " << getName() << "\n"
        << "Severity: " << severityColor << getSeverity() << reset << "\n"
        << "Department: " << getDepartment() << "\n"
        << "Arrival: " << getStringArrivalTime() << "\n"
        << "Gender: " << getGender() << "  Age: " << getAge() << "\n"
        << "Complaints: " << getComplaints() << "\n"
        << "Blood Group: " << getBloodGroup() << "\n"
        << "Diagnosis: " << getDiagnosis();
    return resultingString.str(); // returning the final composed string
}